name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main # O workflow será disparado quando houver um push para a branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest # O workflow será executado em uma máquina Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Faz o checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install # Comando para instalar as dependências do projeto

      - name: Run build script
        run: npm run build # Comando para executar o seu build (substitua se necessário)

  deploy:
    runs-on: ubuntu-latest # O workflow de deploy também será executado no Ubuntu

    needs: build # O deploy só será feito após o build ser bem-sucedido

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Faz o checkout novamente para garantir que o código esteja atualizado

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} # Comando de deploy, usando o token do Firebase
